server:
  port: 8012

spring:
  application:
    name: users-ws

  datasource:
    url: jdbc:postgresql://localhost:5432/users
#    todo: change it so it won't be public
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/