server:
  port: 8012

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/MrCosik/ShopConfig
          username: MrCosik
          password:
          clone-on-start: true
          default-label: main

#  rabbitmq:
#    host: localhost
#    port: 5672